# -*- coding: utf-8 -*-
"""risk_assessment_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10L2fQRj8ioHVkraSa08-9dULDo0iGHiK
"""

import yfinance as yf
import numpy as np
import pandas as pd

stock_symbol = input("Enter Stock Symbol (Example: RELIANCE.NS): ")
index_symbol = "NIFTYBEES.NS"

start_date = "2015-01-01"
end_date = "2025-01-01"

stock_data = yf.download(stock_symbol, start=start_date, end=end_date, auto_adjust=True)
index_data = yf.download(index_symbol, start=start_date, end=end_date, auto_adjust=True)

stock_returns = stock_data["Close"].pct_change().dropna()
index_returns = index_data["Close"].pct_change().dropna()

returns_df = pd.concat([stock_returns, index_returns], axis=1)
returns_df.columns = ["Stock", "Nifty50"]
returns_df = returns_df.dropna()

cov_matrix = np.cov(returns_df["Stock"], returns_df["Nifty50"])
beta = cov_matrix[0][1] / cov_matrix[1][1]

stock_vol = np.std(returns_df["Stock"]) * np.sqrt(252)
nifty_vol = np.std(returns_df["Nifty50"]) * np.sqrt(252)

stock_return = (1 + returns_df["Stock"]).prod() ** (252 / len(returns_df)) - 1
nifty_return = (1 + returns_df["Nifty50"]).prod() ** (252 / len(returns_df)) - 1

sharpe_ratio = stock_return / stock_vol

print("\n------------------------------------------")
print("      Portfolio Risk Analysis Summary     ")
print("------------------------------------------")
print(f"Beta:                      {beta:.4f}")
print(f"Annual Return (Stock):     {stock_return:.2%}")
print(f"Annual Return (Nifty50):   {nifty_return:.2%}")
print(f"Volatility (Stock):        {stock_vol:.2%}")
print(f"Volatility (Nifty50):      {nifty_vol:.2%}")
print(f"Sharpe Ratio (Stock):      {sharpe_ratio:.4f}")
print("------------------------------------------")